steps:
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/nest-docker-repo/nest-app', '.']

  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'asia-southeast1-docker.pkg.dev/$PROJECT_ID/nest-docker-repo/nest-app']

  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: 'gcloud'
    args:
      [
        'run', 'deploy', 'nest-app',
        '--image=asia-southeast1-docker.pkg.dev/$PROJECT_ID/nest-docker-repo/nest-app',
        '--region=asia-southeast1',
        '--platform=managed',
        '--allow-unauthenticated',
        '--set-secrets',
        'DATABASE_URL=projects/$PROJECT_ID/secrets/DATABASE_URL:latest',
        'DIRECT_URL=projects/$PROJECT_ID/secrets/DIRECT_URL:latest',
        'SUPABASE_SERVICE_ROLE_KEY=projects/$PROJECT_ID/secrets/SUPABASE_SERVICE_ROLE_KEY:latest',
        'SUPABASE_ANON_KEY=projects/$PROJECT_ID/secrets/SUPABASE_ANON_KEY:latest',
        'SUPABASE_URL=projects/$PROJECT_ID/secrets/SUPABASE_URL:latest',
        'GOOGLE_PROJECT_ID=projects/$PROJECT_ID/secrets/GOOGLE_PROJECT_ID:latest',
        'GOOGLE_PRIVATE_KEY_ID=projects/$PROJECT_ID/secrets/GOOGLE_PRIVATE_KEY_ID:latest',
        'GOOGLE_PRIVATE_KEY=projects/$PROJECT_ID/secrets/GOOGLE_PRIVATE_KEY:latest',
        'GOOGLE_CLIENT_EMAIL=projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_EMAIL:latest',
        'GOOGLE_CLIENT_ID=projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID:latest',
        'GOOGLE_AUTH_URI=projects/$PROJECT_ID/secrets/GOOGLE_AUTH_URI:latest',
        'GOOGLE_TOKEN_URI=projects/$PROJECT_ID/secrets/GOOGLE_TOKEN_URI:latest',
        'GOOGLE_AUTH_PROVIDER_CERT_URL=projects/$PROJECT_ID/secrets/GOOGLE_AUTH_PROVIDER_CERT_URL:latest',
        'GOOGLE_CLIENT_CERT_URL=projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_CERT_URL:latest',
        'GOOGLE_UNIVERSE_DOMAIN=projects/$PROJECT_ID/secrets/GOOGLE_UNIVERSE_DOMAIN:latest'
      ]

availableSecrets:
  secretManager:
    secrets:
      - env: DATABASE_URL
        versionName: projects/$PROJECT_ID/secrets/DATABASE_URL/versions/latest
      - env: DIRECT_URL
        versionName: projects/$PROJECT_ID/secrets/DIRECT_URL/versions/latest
      - env: SUPABASE_SERVICE_ROLE_KEY
        versionName: projects/$PROJECT_ID/secrets/SUPABASE_SERVICE_ROLE_KEY/versions/latest
      - env: SUPABASE_ANON_KEY
        versionName: projects/$PROJECT_ID/secrets/SUPABASE_ANON_KEY/versions/latest
      - env: SUPABASE_URL
        versionName: projects/$PROJECT_ID/secrets/SUPABASE_URL/versions/latest
      - env: GOOGLE_PROJECT_ID
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_PROJECT_ID/versions/latest
      - env: GOOGLE_PRIVATE_KEY_ID
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_PRIVATE_KEY_ID/versions/latest
      - env: GOOGLE_PRIVATE_KEY
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_PRIVATE_KEY/versions/latest
      - env: GOOGLE_CLIENT_EMAIL
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_EMAIL/versions/latest
      - env: GOOGLE_CLIENT_ID
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_ID/versions/latest
      - env: GOOGLE_AUTH_URI
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_AUTH_URI/versions/latest
      - env: GOOGLE_TOKEN_URI
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_TOKEN_URI/versions/latest
      - env: GOOGLE_AUTH_PROVIDER_CERT_URL
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_AUTH_PROVIDER_CERT_URL/versions/latest
      - env: GOOGLE_CLIENT_CERT_URL
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_CLIENT_CERT_URL/versions/latest
      - env: GOOGLE_UNIVERSE_DOMAIN
        versionName: projects/$PROJECT_ID/secrets/GOOGLE_UNIVERSE_DOMAIN/versions/latest
